config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :groups

  resources :users
  get 'follow_up', to: 'users#follow_up'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  about      :text
#  twitter    :string
#  linkedin   :string
#  facebook   :string
#  github     :string
#  site       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  address    :string
#

class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, through: :memberships

  acts_as_taggable_on :interests
  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    @liv_groups = HTTParty.get("https://api.meetup.com/self/groups?key=#{Rails.application.secrets.meetup_api_key}").body
    @json_groups = JSON.parse(@liv_groups)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/controllers/mail_controller.rb
# class MailController < ApplicationController
#   def index
#   end

#   def create

#     # Get message value from form
#     @message = params


#     # Check if SMTP
#     if @message[:mode] == "SMTP"

#       # Tell notifier action mailer to send via SMTP
#       Notifier.send_email(@message).deliver

#       # Redirect on success
#       redirect_to root_path, notice: 'Message was sent via SMTP.'


#     # Else send via API
#     else

#       # First, instantiate the Mailgun Client with your API key
#       mg_client = Mailgun::Client.new ENV['MAILGUN_API_KEY']

#       # Define your message parameters
#       html_output = render_to_string template: "notifier/send_email"
#       message_params = {:from    => 'Mailgun Test Project <postmaster@' + ENV['MAILGUN_DOMAIN'] + ">",
#                         :to      => @message[:to],
#                         :subject => 'Mailgun message via API',
#                         :text    => @message[:body],
#                         :html    => html_output.to_str,
#                         "o:tag"  => 'test'}

#       # Send your message through the client
#       mg_client.send_message ENV['MAILGUN_DOMAIN'], message_params

#       # Redirect on success
#       redirect_to root_path, notice: 'Message was sent via API.'
#     end
#   end
# end

app/controllers/users_controller.rb
require 'rest-client'

class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def send_simple_message
    RestClient.post "https://api:#{Rails.application.secrets.mailgun_api_key}"\
    "@api.mailgun.net/v3/sandbox6f38c47038a64b02b8e1a09650b98a67.mailgun.org/messages",
    :from => "Mailgun Sandbox <postmaster@sandbox6f38c47038a64b02b8e1a09650b98a67.mailgun.org>",
    :to => "lucybain@gmail.com",
    :subject => "Hello #{@user.name}",
    :text => "Congratulations #{@user.name}, you are now a keenbean"
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.first
    # send_simple_message
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # send_simple_message

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow_up
    @user = User.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :about, :twitter, :linkedin, :facebook, :github, :site)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups near you</h1>
<div class="row groups-listing">
  <ul>
    <% @groups.each do |group| %>

      <div class="col-md-4">
        <div class="card text-xs-center", style: style="background-image: url('<%= group.image %>')">
          <div class="card-block">
            <h4 class="card-title"><%= group['name'] %></h4>
            <%= link_to 'Sign up', new_user_path, :class => "btn btn-primary"%>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title> Coffee catch ups </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Roboto|Source+Sans+Pro" rel="stylesheet">
  <link rel="stylesheet" href="override.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand"><%= image_tag("logo.png") %></span>
      <div class="app_name">Coffee catch ups</div>
    </div>
  </div>
</nav>
<main class="<%= controller_name %> <%= action_name %>">
  <%= yield %>
</main>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %><br>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :about %><br>
      <%= f.text_area :about, class: 'form-control' %>
    </div>
    <p>Everything else is optional, but the more you share the more likely you are to have a good match!</p>
    <div class="form-group">
      <%= f.label :twitter %><br>
      <%= f.text_field :twitter, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :linkedin %><br>
      <%= f.text_field :linkedin, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :facebook %><br>
      <%= f.text_field :facebook, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :github %><br>
      <%= f.text_field :github, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :site %><br>
      <%= f.text_field :site, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.button :submit, class: 'btn btn-default' do %>
        Join!
      <% end %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/follow_up.html.erb
<h1>Catchup feedback </h1>
<p> We hope you had a great time on your coffee catch up with Liv this week. To help us provide the best experience possible we'd like some feedback from you. </p>
<%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label 'Did you two catch up?' %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'How was the catch up?' %><br>
      <%= f.text_area :email, class: 'form-control' %>
    </div>
    <p>
      We'd love to match you again for next week.  Are you keen?
    </p>
    <div class="form-group">
      <div>
    		<%= radio_button_tag(:yes, "Absolutely!") %>
    		<%= label_tag(:age_child, "Absolutely!") %><br/>
    		<%= radio_button_tag(:yes, "No") %>
    		<%= label_tag(:age_child, "Not right now") %>
  	  </div>
    </div>

    <div class="actions">
      <button class='btn btn-default'%>
        Submit
	  </button>
    </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>About</th>
      <th>Twitter</th>
      <th>Linkedin</th>
      <th>Facebook</th>
      <th>Github</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.about %></td>
        <td><%= user.twitter %></td>
        <td><%= user.linkedin %></td>
        <td><%= user.facebook %></td>
        <td><%= user.github %></td>
        <td><%= user.site %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag("liv.jpg", class: "profile-pic") %>
  </div>
  <div class="col-md-8">
    <h1><%= @user.name %></h1>
    <p>Developer</p>
    <p>
      <%= @user.about %>
    </p>
    <p>
      <%= fa_icon "envelope" %>
      <%= mail_to(@user.email) %>
    </p>
    <% if @user.twitter.present? %>
    <p>
      <%= fa_icon "twitter" %>
      <%= link_to(@user.twitter.sub(/^https?\:\/\//, '').sub(/^www./,''), @user.twitter) %>
    </p>
    <% end %>

    <% if @user.linkedin.present? %>
    <p>
      <%= fa_icon "linkedin" %>
      <%= link_to(@user.linkedin.sub(/^https?\:\/\//, '').sub(/^www./,''), @user.linkedin) %>
    </p>
    <% end %>

    <% if @user.facebook.present? %>
    <p>
      <%= fa_icon "facebook" %>
      <%= link_to(@user.facebook.sub(/^https?\:\/\//, '').sub(/^www./,''), @user.facebook) %>
    </p>
    <% end %>

    <% if @user.github.present? %>
    <p>
      <%= fa_icon "github" %>
      <%= link_to(@user.github.sub(/^https?\:\/\//, '').sub(/^www./,''), @user.github) %>
    </p>
    <% end %>

    <% if @user.site.present? %>
    <p>
      <strong>Site:</strong>
      <%= link_to(@user.site.sub(/^https?\:\/\//, '').sub(/^www./,''), @user.site) %>
    </p>
    <% end %>

  </div>
</div>